//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogId { get; set; }
        public string LType { get; set; }
        public System.DateTime LDate { get; set; }
        public string LDetails { get; set; }
        public int CustId { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
